### ISSUE TITLE
reviewdog 에러

### ISSUE THREAD

**Issue by xornjswldh** [KEA-DoKebi/dalkom-backend#222]
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/038c8d05-ff21-4bdc-a4eb-c8a7fb80f64d)
상수 이름에 언더스코어는 허용되는데, 언더스코어도 허용되지 않는 규칙으로 검사중

![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/3100801e-e988-4965-9343-d1b8352dd739)
들여쓰기를 여전히 이상하게 인식함. 탭키의 공백 수 설정은 코드 스타일 xml 파일을 통해 백엔드 팀원 전체에게 적용된 설정이라 문제가 생길 가능성 적음. 띄어쓰기 4개(혹은 8개) 등 탭키가 아닌 띄어쓰기 들여쓰기 또한, 파일이 저장될 때 자동으로 탭키로 변경되는 설정임.

@eastlighting1

**Comment by eastlighting1** [comment]
반영 완료되었습니다
