### ISSUE TITLE
reviewdog False Positive

### ISSUE THREAD

**Issue by xornjswldh** [KEA-DoKebi/dalkom-backend#229]
코드 컨벤션
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/778e2ecb-e0a8-4e5d-b849-812962499f16)

False Positive 사례
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/7955c8be-0b8f-4e6c-9a56-82a9762457ff)

발생 위치
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/2731f723-873f-40c7-8159-f2e61ea8f346)

@eastlighting1

**Comment by eastlighting1** [comment]
확인
