### ISSUE TITLE
reviewDog FalsePositive 2

### ISSUE THREAD

**Issue by xornjswldh** [KEA-DoKebi/dalkom-backend#230]
에러 메세지
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/0ba75dbd-f8de-4ec8-9ed0-8a2ad2a021ee)
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/a594b4cc-12ca-4b0f-86f7-c0e0b309b263)

실제 코드 길이
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/da6040a3-49ef-4606-971b-893617538402)
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/86345585/17e1e93d-0764-4ce1-8f8f-8663343f28da)

**Comment by eastlighting1** [comment]
확인
