### ISSUE TITLE
LocalDateTime인거 LocalDate로 다 바꾸나요?

### ISSUE THREAD

**Issue by changmeen** [KEA-DoKebi/dalkom-backend#266]
InquiryListByUserResponse에서 현재 LocalDateTime으로 사용중인데 얘처럼 LocalDateTime 쓰는 얘들 다 LocalDate로 변경해서 사용하는건지 모르겠네요 정해진게 있을까요?

**Comment by xornjswldh** [comment]
입사일은 DB에 LocalDate의 형식으로 들어가있어 어쩔 수 없이 LocalDate를 사용중이지만, LocalDateTime이 기본으로 알고있습니다.
입사일을 다루는 변수가 아닌데 LocalDate를 사용하는건 LocalDateTIme으로 바꿔주시면 감사하겠습니다.

**Comment by xornjswldh** [comment]
입사일은 DB에 LocalDate의 형식으로 들어가있어 어쩔 수 없이 LocalDate를 사용중이지만, 그 외에는 LocalDateTime이 기본으로 알고있습니다.
입사일을 다루는 변수가 아닌데 LocalDate를 사용하는건 LocalDateTIme으로 바꿔주시면 감사하겠습니다.
