### ISSUE TITLE
[리뷰] 업데이트 Validation 에러 발생

### ISSUE THREAD

**Issue by changmeen** [KEA-DoKebi/dalkom-backend#313]
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/73987361/514dd65e-4025-4a39-badf-7b14b47363d2)
![image](https://github.com/KEA-DoKebi/dalkom-backend/assets/73987361/76f4d18f-8912-4ad7-a996-dd4fce977c15)

elatic 로그를 확인해보니 NotBlank 에러가 발생하는데 별점만 수정하고 수정하기 버튼을 누른 상태인거라 아마 내용물이 변하지 않아서 ""상태 혹은 null값으로 BE로 넘어가서 vadliation에서 NotBlank에서 에러 처리를 하는 것 같습니다.

**Comment by xornjswldh** [comment]
해결
